version: '3.7'
services:
  isucon:
    container_name: isucon_centos7_maria5
    build: .
    tty: true
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - ./isucon8-practice:/isucon8-practice