version: '3.7'
services:
  isucon:
    container_name: isucon_ubuntu18_mysql8
    image: isucon_ubuntu18_mysql8:latest
    tty: true
    privileged: true
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./isucon:/isucon
    command: /usr/sbin/mysqld
    ports:
      - "8080:8080"